version: '3'
services:
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
      - ./www/:/var/www/
    ports:
      - 80:80
    depends_on:
      - php74
      - php81
    environment:
      - TZ=Asia/Shanghai
  php74:
    build:
      context: ./services/php74
    volumes:
      - ./services/php74/php.ini:/usr/local/etc/php/php.ini
      - ./services/php74/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php74/:/var/log/php/
      - ./www/:/var/www/
    environment:
      - TZ=Asia/Shanghai
  php81:
    build:
      context: ./services/php81
    volumes:
      - ./services/php81/php.ini:/usr/local/etc/php/php.ini
      - ./services/php81/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php81/:/var/log/php/
      - ./www/:/var/www/
    environment:
      - TZ=Asia/Shanghai
  mysql80:
    image: mysql:8.0.30
    volumes:
      - ./services/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql80/:/var/lib/mysql/:rw
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp:unconfined
  redis62:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis62/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis62/:/data/:rw
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
  redis70:
    image: redis:7.0.4-bullseye
    volumes:
      - ./services/redis70/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis70/:/data/:rw
    ports:
      - 6380:6379
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
  mongo50:
    image: mongo:5.0.10
    volumes:
      - ./services/mongo50/mongod.conf.orig:/etc/mongod.conf.orig
      - ./data/mongo50/:/data/db/
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=auth123
      - TZ=Asia/Shanghai
    command: --auth
  openresty121:
    build:
      context: ./services/openresty121
    volumes:
      - ./services/openresty121/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./services/openresty121/conf.d/:/etc/nginx/conf.d/
      - ./logs/openresty121/:/usr/local/openresty/nginx/logs/
      - ./www/:/var/www/
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Shanghai
  redis-cluster:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/:/usr/local/etc/redis/
      - ./data/redis-cluster/:/data/
    ports:
      - 7001-7003:7001-7003
      - 17001-17003:17001-17003
    command: 
      - /bin/bash
      - -c
      - |
        redis-server /usr/local/etc/redis/7001/redis.conf &
        redis-server /usr/local/etc/redis/7002/redis.conf &
        redis-server /usr/local/etc/redis/7003/redis.conf
    environment:
      - TZ=Asia/Shanghai


