version: '3'
services:
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
      - ./www/:/var/www/
    ports:
      - 80:80
    depends_on:
      - php74
      - php81
    environment:
      - TZ=Asia/Shanghai
  php74:
    build:
      context: ./services/php74
    volumes:
      - ./services/php74/php.ini:/usr/local/etc/php/php.ini
      - ./services/php74/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php74/:/var/log/php/
      - ./www/:/var/www/
    environment:
      - TZ=Asia/Shanghai
  php81:
    build:
      context: ./services/php81
    volumes:
      - ./services/php81/php.ini:/usr/local/etc/php/php.ini
      - ./services/php81/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php81/:/var/log/php/
      - ./www/:/var/www/


