version: '3'
services:
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
      - ./www/:/var/www/
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai


